name: thesis
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.16.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.1
  - copulas=0.12.1
  - ctgan=0.11.0
  - cudatoolkit=11.3.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - deepecho=0.7.0
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.6.3
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - getopt-win32=0.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.13
  - graphviz=7.1.0
  - gts=0.7.6
  - h11=0.14.0
  - harfbuzz=6.0.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - icc_rt=2022.1.0
  - icu=72.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgd=2.3.3
  - libglib=2.78.4
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook-shim=0.2.3
  - numexpr=2.10.1
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.1
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - pango=1.50.12
  - parso=0.8.3
  - pcre2=10.42
  - pillow=11.1.0
  - pip=24.2
  - pixman=0.44.2
  - platformdirs=4.3.7
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-graphviz=0.20.3
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - rdt=1.15.0
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - s3transfer=0.11.4
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - sdmetrics=0.19.0
  - sdv=1.19.0
  - send2trash=1.8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tenacity=9.0.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - vc=14.40
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - boto3==1.37.18
      - botocore==1.37.18
      - contourpy==1.3.1
      - cycler==0.12.1
      - faker==35.2.0
      - flatbuffers==25.1.24
      - fonttools==4.56.0
      - fsspec==2024.12.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - h5py==3.12.1
      - keras==3.8.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - namex==0.0.8
      - narwhals==1.26.0
      - numpy==2.2.4
      - opt-einsum==3.4.0
      - optree==0.14.0
      - plotly==6.0.0
      - protobuf==5.29.3
      - pyparsing==3.2.1
      - rich==13.9.4
      - seaborn==0.13.2
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tzdata==2025.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
